### ISSUE TITLE
Exit Code 6 after placing down creative frame

### ISSUE THREAD

**Issue by eassq** [CreativeMD/LittleFrames#92]
hi, so whenever i place down a creative frame, the game crashes with exit code 6.
log: 
[hs_err_pid100639.log](https://github.com/user-attachments/files/17637406/hs_err_pid100639.log)

**Comment by SrRapero720** [comment]
LittleFrames 1.12.2 is not supported anymore

Crash is caused by VLCJ attemping to load a awt component, that awt component loads a LibX11 utility for multithreading which causes the issue

Problem comes  might comes from
1. Your JRE/JDK version
2. Drivers and linux packages (updates all)
3. Broken drivers (update all)

Anyway, blake can solve it removing all vlcj integrations with awt (which is already solved in WaterMedia)

**Comment by eassq** [comment]
so i should install the water media versions of 1.12.2? because i don't know how to update all of my drivers

**Comment by SrRapero720** [comment]
watermedia is not longer available on 1.12.2. firsts releases has a lot of problems (triggering untrackable exceptions on other mods).

**Comment by eassq** [comment]
so how do i proceed?

**Comment by CreativeMD** [comment]
Sorry, but 1.12.2 is not supported anymore. I cannot really help you there.

**Comment by eassq** [comment]
fuck
